apiVersion: v1
data:
  alertmanager.yml: |-
    global:
    receivers:
      - name: default-receiver
        webhook_configs:
        - url: 'http://<**edit_me**>:9999'
    route:
      group_by: ['alertname','instance','kubernetes_namespace','pod','container']
      group_wait: 10s
      group_interval: 5m
      receiver: default-receiver
      repeat_interval: 3h
      routes:
      - receiver: default-receiver
        match:
          alertname: ICPMonitoringHeartbeat
        repeat_interval: 5m
kind: ConfigMap
metadata:
  labels:
    app: monitoring-prometheus
    chart: ibm-icpmonitoring-1.1.0
    component: alertmanager
    heritage: Tiller
    release: monitoring
  name: monitoring-prometheus-alertmanager
  namespace: kube-system
  selfLink: /api/v1/namespaces/kube-system/configmaps/monitoring-prometheus-alertmanager
